apiVersion: training.educates.dev/v1beta1
kind: TrainingPortal
metadata:
  name: lab-kpack
spec:
  portal:
    registration:
      type: anonymous
    updates:
      workshop: true
  workshops:
  - name: lab-kpack
    capacity: 1
    expires: 30m
    orphaned: 5m
