apiVersion: training.educates.dev/v1beta1
kind: TrainingPortal
metadata:
  name: app-engine 
  annotations:
    kapp.k14s.io/update-strategy: always-replace
spec:
  portal:
    title: Tanzu Application Engine demo 
    password: welcome
    registration:
      type: anonymous
      enabled: true
    updates:
      workshop: true
    sessions:
      maximum: 45
  workshops:
    - name: app-engine
      expires: 360m
      orphaned: 120m
      capacity: 20
      reserved: 1

