apiVersion: training.educates.dev/v1beta1
kind: Workshop
metadata:
  name: lab-kpack-kubecon
spec:
  title: Building Images with kpack
  description: Learn how kpack can help you build images securely and efficiently at scale
  url: https://github.com/vmware-tanzu-labs/lab-kpack-kubecon
  workshop:
    files:
    - image:
        url: $(image_repository)/lab-kpack-kubecon-files:latest
      includePaths:
      - /workshop/**
  session:
    namespaces:
      budget: custom
    applications:
      terminal:
        enabled: true
        layout: split
      vcluster:
        enabled: true
      registry:
        enabled: true
      docker:
        enabled: true
      git:
        enabled: true
      editor:
        enabled: true
    objects:
    - apiVersion: data.packaging.carvel.dev/v1alpha1
      kind: Package
      metadata:
        name: kpack.community.tanzu.vmware.com.0.5.3
        namespace: $(session_namespace)-vc
      spec:
        refName: kpack.community.tanzu.vmware.com
        version: 0.5.3
        capacityRequirementsDescription: Registry with > 1GB available space
        releaseNotes: https://github.com/pivotal/kpack/releases/tag/v0.5.3
        valuesSchema:
          openAPIv3:
            title: kpack.tanzu.vmware.com values schema
            properties:
              kp_default_repository:
                type: string
                description: docker repository
                examples:
                  - registry.io/kpack
              kp_default_repository_secret:
                type: object
                description: Secret reference for kp_default_repository credentials. Mutually exclusive with kp_default_repository_username/password. Requires Carvel secretgen-controller.
                properties:
                  name:
                    description: Secret name for kp_default_repository credentials of type kubernetes.io/dockerconfigjson.
                    type: string
                  namespace:
                    description: Secret namespace for kp_default_repository credentials.
                    type: string
              kp_default_repository_username:
                type: string
                description: registry username
                examples:
                  - janedoe@vmware.com
              kp_default_repository_password:
                type: string
                description: registry password
                examples:
                  - password
              http_proxy:
                type: string
                description: the HTTP proxy to use for network traffic
              https_proxy:
                type: string
                description: the HTTPS proxy to use for network traffic.
              no_proxy:
                type: string
                description: A comma-separated list of hostnames, IP addresses, or IP ranges in CIDR format that should not use a proxy
              ca_cert_data:
                type: string
                description: CA Certificate to be injected into the kpack controller trust store for communicating with self signed registries.
        template:
          spec:
            fetch:
              - imgpkgBundle:
                  image: projects.registry.vmware.com/kpack/release@sha256:5c474f75dbb77967cfe6849b741d32c71ea511db8cf6f931ad6acce3d2c53876
            template:
              - ytt:
                  paths:
                    - config/
              - kbld:
                  paths:
                    - '-'
                    - .imgpkg/images.yml
            deploy:
              - kapp:
                  rawOptions:
                    - "--app-changes-max-to-keep=5"
    - apiVersion: packaging.carvel.dev/v1alpha1
      kind: PackageInstall
      metadata:
        name: kpack
        namespace: $(session_namespace)-vc
      spec:
        packageRef:
          refName: kpack.community.tanzu.vmware.com
          versionSelection:
            constraints: 0.5.3
        values:
          - secretRef:
              name: kpack-values
        cluster:
          namespace: default
          kubeconfigSecretRef:
            name: $(vcluster_secret)
            key: config
        noopDelete: true
        syncPeriod: 24h
    - apiVersion: v1
      kind: Secret
      metadata:
        name: kpack-values
        namespace: $(session_namespace)-vc
      stringData:
        values.yml: |-
          kp_default_repository: $(registry_host)/kp    
          kp_default_repository_username: $(registry_username)    
          kp_default_repository_password: $(registry_password)
